### ISSUE TITLE
HOW TO INSTALL

### ISSUE THREAD

**Issue by Symbyos83** [kamaradclimber/home_assistant-ble#11]
Hi, I could not figure out how to install all this. I arrive at the line "Run home_assistant-ble [your config file] binary." and I can not figure out where my config file is located. Can you explain it better? thank you.

**Comment by kamaradclimber** [comment]
Hello,
configuration file is described at the bottom of the readme.
Create one somewhere (in your home directory for instance) and launch `home_assistant-ble [path to your configuration file]`.

There is nothing more
