### ISSUE TITLE
Multiple installs

### ISSUE THREAD

**Issue by privatesam** [kamaradclimber/home_assistant-ble#15]
Not really an issue but a query.

If I were to run this software on multiple Pi's around my house all reporting to the same HA instance would it still work as intended?  I'm using this to detect whether my dog is in the house I have a Pi downstairs and upstairs if I run this on both instances I assume it just updates the HA instance whenever it see's the bt tag on the dog collar.  What I'm conerned about is when the dog is away from one of the Pi's it will report the dog as disappeared to the HA instance and may override the fact it has in fact now appeared on the other pi.  

Either way thank you very much for this software its very useful and I appreciate it!

**Comment by kamaradclimber** [comment]
I think indeed your dog will be detected away by one of the raspberry and marked as away. The other raspberry would consider it is still home and would not update home-assistant.

It would be possible to deal with this if the software was checking home-assistant for device "at home" frequently. In this case, you would see the dog away and a few seconds later at home again.

**Comment by privatesam** [comment]
Thanks thats what I thought.  Theres this code/application which is meant to handle this kind of scenario: https://github.com/Odianosen25/Monitor-App  but its heavy, clunky and so far for me not working!  I love the simplicity and ease of this app.  To be honest the RPi3 bluetooth is pretty powerful and can sense when the dog is present in most of the house, I just figure as I have 2 RPi it would be worth utilising both for dog detection.  I'm going to close this now as its not an issue.  Thanks for the reply.
