### ISSUE TITLE
Overriding device's name with device's ID from known_devices.yaml

### ISSUE THREAD

**Issue by kirichkov** [kamaradclimber/home_assistant-ble#4]
https://github.com/kamaradclimber/home_assistant-ble/blob/master/lib/home_assistant/ble.rb#L49

I see that you override the device's friendly name on purpose. Can you explain to me what's your reasoning behind it? For me that was unexpected when the device's name changed to it's `dev_id`.

**Comment by kirichkov** [comment]
I think I figured it out. Instead of using `/api/services/device_tracker/see` you are directly changing the state via `/api/states/`. I am not sure, however, that this will trigger an event for the state change, i.e. - state-based automations might not be running. 

I think it's better to use the device_tracker API, instead of directly updating the state of the device.

**Comment by kamaradclimber** [comment]
You're right this route should be better.

Le sam. 1 avr. 2017 13:21, Georgi Kirichkov <notifications@github.com> a
écrit :

**Comment by kamaradclimber** [comment]
fixed by #5
